
[workspace]
package.version = "0.1.0"
package.edition = "2024"
package.license = "MIT"
package.repository = "https://github.com/tirbofish/proton-sdk-rs2"
package.readme = "README.md"
package.authors = ["Thribhu K <4tkbytes@pm.me>"]

resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
semver = "1.0"
anyhow = "1.0"
prost-build = "0.11"
prost = "0.11"
prost-types = "0.11"
reqwest = { version = "0.13", features = ["json"] }
proton-srp = { git = "https://github.com/ProtonMail/proton-crypto-rs", features = ["pgpinternal"]}
tokio = { version = "1.50", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
dashmap = "6.1"
http = "1.4"
async-trait = "0.1"
base64 = "0.22"
futures = "0.3"
proton-crypto = { version = "*", registry = "proton" }
ron = "0.12"
chrono = { version = "0.4", features = ["serde"]}
proton-rpgp = { git = "https://github.com/ProtonMail/proton-crypto-rs" }
bytes = "1.11"
bitflags = "2.11"
sha2 = "0.11.0-rc.5"
sha1 = "0.10.6"
hmac = "0.13.0-rc.5"
hex = "0.4.3"
serde_with = "3.18.0"
serde_repr = "0.1.20"
reqwest-middleware = { version = "0.5.1", features = ["json", "multipart"] }
rand = "0.8.5"
smallvec = "1.15.1"
thiserror = "2.0.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
parking_lot = { version = "0.12.5", features = ["deadlock_detection"] }
mime_guess = "2.0.5"
image = { version = "0.25.5", features = ["png", "jpeg", "webp"] }
rpassword = "7.4.0"
rusqlite = { version = "0.32", features = ["bundled"] }
aes-gcm = "0.10"
