[package]
name = "proton-drive"
version = "0.1.0"
edition = "2024"

[dependencies]
proton-sdk-rs2 = { path = "../proton-sdk-rs2" }

proton-crypto.workspace = true
reqwest.workspace = true
async-trait.workspace = true
anyhow.workspace = true
tokio.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
proton-rpgp.workspace = true
prost.workspace = true
prost-types.workspace = true
base64.workspace = true
log.workspace = true
bytes.workspace = true
http.workspace = true
sha2 = "0.11.0-rc.5"
hmac = "0.13.0-rc.5"
hex = "0.4.3"
serde_with = "3.18.0"
serde_repr = "0.1.20"
bitflags = {version = "2.11.0", features = ["serde"]}
reqwest-middleware = { version = "0.5.1", features = ["json", "multipart"] }
rand = "0.8.5"
smallvec = "1.15.1"
thiserror = "2.0.18"
tracing = "0.1.44"
parking_lot = "0.12.5"
mime_guess = "2.0.5"

[build-dependencies]
prost-build.workspace = true
